---
name: Data Ingester Production Deployment

on:
  push:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:

env:
  RUST_VERSION: "nightly-2026-02-04"

permissions:
  # actions: read|write|none
  # attestations: read|write|none
  # checks: read|write|none
  # contents: read
  # deployments: read|write|none
  id-token: write
  # iessues: read|write|none
  # nmodels: read|none
  # discussions: read|write|none
  # packages: read|write|none
  # pages: write
  # pull-requests: read|write|none
  # security-events: read|write|none
  # statuses: read|write|none

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-04
          targets: x86_64-unknown-linux-musl

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}/target
          key: cargo_audit-${{ steps.toolchain.outputs.name}} }}

      - name: cargo audit
        run: cargo install cargo-audit; cargo audit

  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-04
          targets: x86_64-unknown-linux-musl
          components: rustfmt

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}/target
          key: cargo-fmt-${{ steps.toolchain.outputs.name}}-${{ hashFiles('Cargo.lock') }}

      - name: cargo fmt
        run: cargo fmt --check

  terraform_validate_red:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Deploy terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform version
        run: terraform -version

        # Terraform
      - name: Run terraform
        run: cd terraform/red; terraform init -backend=false; terraform validate

  terraform_fmt:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Deploy terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform version
        run: terraform -version

        # Terraform
      - name: Run terraform
        run: cd terraform; terraform fmt -check -recursive .

  clippy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-04
          targets: x86_64-unknown-linux-musl
          components: clippy

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}/target
          key: cargo-clippy-${{ steps.toolchain.outputs.name}}-${{ hashFiles('Cargo.lock') }}

      - name: cargo clippy
        run: cargo clippy

  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-04
          targets: x86_64-unknown-linux-musl

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}/target
          key: cargo_test-${{ steps.toolchain.outputs.name}}-${{ hashFiles('Cargo.lock') }}

      - name: cargo test
        run: cargo test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: musl-tools
          version: 1.0

      - name: toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-02-04
          targets: x86_64-unknown-linux-musl
          components: rust-src

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}/target
          key: cargo_build_cache-rust-target-${{ steps.toolchain.outputs.name}}-${{ hashFiles('Cargo.lock') }}

      - name: cargo build
        run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: SHA256 for release binary
        run: sha256sum target/x86_64-unknown-linux-musl/release/ssphp-github-webhooks

      - name: Upload bin
        uses: actions/upload-artifact@v4
        with:
          name: ssphp-github-webhooks_${{ github.sha }}
          path: target/x86_64-unknown-linux-musl/release/ssphp-github-webhooks
          if-no-files-found: error
          compression-level: 9

  terraform_deploy:
    needs: [audit, test, build]

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ssphp-github-webhooks_${{ github.sha }}
          path: terraform/github_webhooks/function_zip/

      - name: Set binary to +x
        run: chmod +x terraform/github_webhooks/function_zip/ssphp-github-webhooks

      - name: SHA256 for release binary
        run: sha256sum terraform/github_webhooks/function_zip/ssphp-github-webhooks

      - name: Deploy terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Terraform version
        run: terraform -version

        # Terraform
      - name: Run terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: cd terraform/red; terraform init -upgrade; terraform apply -auto-approve
